"""Add Drug table

Revision ID: 2fe9b486ef67
Revises: 7dc43c184ced
Create Date: 2026-08-24 01:45:18.395575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe9b486ef67'
down_revision: Union[str, Sequence[str], None] = '7dc43c184ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.create_table('drugs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('awareClass', postgresql.ENUM('ACCESS', 'WATCH', 'RESERVE', name='aware_class_enum', create_type=False), nullable=True),
    sa.Column('isCia', sa.Boolean(), nullable=True),
    sa.Column('formulation', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs')
    # ### end Alembic commands ###
