"""init

Revision ID: 7dc43c184ced
Revises: 
Create Date: 2026-08-23 19:34:55.095925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc43c184ced'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('activeFarms', sa.Integer(), nullable=False),
    sa.Column('totalHeadcount', sa.Integer(), nullable=False),
    sa.Column('riskLevel', sa.String(), nullable=False),
    sa.Column('topConcern', sa.String(), nullable=False),
    sa.Column('complianceRate', sa.Float(), nullable=False),
    sa.Column('dataSeries', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amrIndex', sa.Float(), nullable=False),
    sa.Column('activeAlerts', sa.Integer(), nullable=False),
    sa.Column('complianceRate', sa.Float(), nullable=False),
    sa.Column('samplingRate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'VET', 'LAB_TECHNICIAN', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('farms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('DAIRY', 'POULTRY', 'LIVESTOCK', 'MIXED', name='farm_kind_enum'), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('operatedByFarmer', sa.Boolean(), nullable=True),
    sa.Column('ownerId', sa.String(), nullable=True),
    sa.Column('cowsCount', sa.Integer(), nullable=True),
    sa.Column('buffaloesCount', sa.Integer(), nullable=True),
    sa.Column('goatsCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('vciRegNo', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=False),
    sa.Column('isCurrentUser', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('admin_anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=True),
    sa.Column('farmName', sa.String(), nullable=False),
    sa.Column('species', sa.Enum('COW', 'BUFFALO', 'GOAT', 'POULTRY', name='species_enum'), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('drug', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='anomaly_severity_enum'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('dateLabel', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=False),
    sa.Column('species', sa.Enum('COW', 'BUFFALO', 'GOAT', 'POULTRY', name='species_enum'), nullable=False),
    sa.Column('isFlock', sa.Boolean(), nullable=True),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('dateOfBirth', sa.DateTime(), nullable=True),
    sa.Column('productionType', sa.String(), nullable=False),
    sa.Column('registeredOn', sa.DateTime(), nullable=True),
    sa.Column('onFarmerRoster', sa.Boolean(), nullable=True),
    sa.Column('careStatus', sa.Enum('UNDER_TREATMENT', 'IMPROVED', 'RECOVERED', 'NO_CHANGE', 'HEALTHY', name='care_status_enum'), nullable=True),
    sa.Column('lastFollowUp', sa.DateTime(), nullable=True),
    sa.Column('followUpDue', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_animal_care', 'animals', ['careStatus'], unique=False)
    op.create_index('idx_animal_farm', 'animals', ['farmId'], unique=False)
    op.create_index('idx_animal_species', 'animals', ['species'], unique=False)
    op.create_table('medicine_stocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('recentUsage', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('RESTOCK', 'MONITOR', 'GOOD', name='stock_level_enum'), nullable=True),
    sa.Column('usageTotal', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmId', 'name', name='uq_stock_farm_name')
    )
    op.create_table('health_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('animalId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('onset', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animalId'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_animal', 'health_events', ['animalId'], unique=False)
    op.create_table('lab_samples',
    sa.Column('dispatchId', sa.String(), nullable=False),
    sa.Column('sampleId', sa.String(), nullable=False),
    sa.Column('product', sa.Enum('MILK', 'MEAT', 'EGGS', name='product_type_enum'), nullable=False),
    sa.Column('productSub', sa.String(), nullable=False),
    sa.Column('productLabel', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=True),
    sa.Column('animalId', sa.String(), nullable=True),
    sa.Column('sourceName', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('scheduledFor', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('AWAITING_RECEIPT', 'RECEIVED', 'TESTING', 'AWAITING_VERIFICATION', 'VERIFIED', 'ON_HOLD', name='lab_stage_enum'), nullable=True),
    sa.Column('receivedOn', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animalId'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('dispatchId'),
    sa.UniqueConstraint('sampleId')
    )
    op.create_index('idx_ls_stage', 'lab_samples', ['stage'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=False),
    sa.Column('animalId', sa.String(), nullable=False),
    sa.Column('vetId', sa.String(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SIGN_REQUIRED', 'UNSIGNED_EMERGENCY', 'SIGNED', 'COUNTERSIGNED', 'VOIDED', name='prescription_status_enum'), nullable=False),
    sa.Column('aware', sa.Enum('ACCESS', 'WATCH', 'RESERVE', name='aware_class_enum'), nullable=True),
    sa.Column('cia', sa.Boolean(), nullable=True),
    sa.Column('drug', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('dateLabel', sa.String(), nullable=False),
    sa.Column('stewardshipGuidance', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('previousTreatment', sa.JSON(), nullable=True),
    sa.Column('treatmentHistory', sa.JSON(), nullable=True),
    sa.Column('signedBy', sa.String(), nullable=True),
    sa.Column('signedAt', sa.DateTime(), nullable=True),
    sa.Column('signatureRef', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animalId'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['vetId'], ['vets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rx_animal', 'prescriptions', ['animalId'], unique=False)
    op.create_index('idx_rx_farm', 'prescriptions', ['farmId'], unique=False)
    op.create_index('idx_rx_status', 'prescriptions', ['status'], unique=False)
    op.create_table('lab_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dispatchId', sa.String(), nullable=False),
    sa.Column('refNo', sa.String(), nullable=False),
    sa.Column('verifiedBy', sa.String(), nullable=False),
    sa.Column('verifiedOn', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('statusColor', sa.String(), nullable=True),
    sa.Column('mrlDrug', sa.String(), nullable=False),
    sa.Column('mrlMeasured', sa.Float(), nullable=False),
    sa.Column('mrlLimit', sa.Float(), nullable=False),
    sa.Column('mrlUnit', sa.String(), nullable=True),
    sa.Column('mrlRatio', sa.Float(), nullable=False),
    sa.Column('mrlVerdict', sa.String(), nullable=False),
    sa.Column('mrlVerdictOk', sa.Boolean(), nullable=True),
    sa.Column('withdrawalDrug', sa.String(), nullable=False),
    sa.Column('withdrawalAdministered', sa.String(), nullable=False),
    sa.Column('withdrawalCompleted', sa.String(), nullable=False),
    sa.Column('withdrawalStatus', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('outcomeOk', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatchId'], ['lab_samples.dispatchId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatchId'),
    sa.UniqueConstraint('refNo')
    )
    op.create_table('lab_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dispatchId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('checks', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('state', sa.Enum('DONE', 'ACTIVE', 'PENDING', name='lab_test_state_enum'), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dispatchId'], ['lab_samples.dispatchId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lt_dispatch', 'lab_tests', ['dispatchId'], unique=False)
    op.create_table('prescription_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drugName', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('prescriptionId', sa.String(), nullable=True),
    sa.Column('isEmergencyException', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prescriptionId'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('animalId', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=False),
    sa.Column('prescriptionId', sa.String(), nullable=True),
    sa.Column('drug', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('administeredLabel', sa.String(), nullable=False),
    sa.Column('administeredOn', sa.DateTime(), nullable=False),
    sa.Column('phase', sa.Enum('ACTIVE', 'WITHDRAWAL', 'COMPLETED', name='treatment_phase_enum'), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=True),
    sa.Column('labAssay', sa.Enum('WITHIN_MRL', 'UNAVAILABLE', 'EXCEEDED', name='lab_assay_verdict_enum'), nullable=True),
    sa.Column('feedBatch', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animalId'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['prescriptionId'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trt_animal', 'treatments', ['animalId'], unique=False)
    op.create_index('idx_trt_farm', 'treatments', ['farmId'], unique=False)
    op.create_index('idx_trt_phase', 'treatments', ['phase'], unique=False)
    op.create_table('farmer_dispatches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmId', sa.String(), nullable=False),
    sa.Column('animalId', sa.String(), nullable=False),
    sa.Column('product', sa.Enum('MILK', 'MEAT', 'EGGS', name='product_type_enum'), nullable=False),
    sa.Column('dateLabel', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CLEARED', 'WITHDRAWAL', 'BLOCKED', name='dispatch_status_enum'), nullable=False),
    sa.Column('treatmentId', sa.String(), nullable=True),
    sa.Column('labDispatchId', sa.String(), nullable=True),
    sa.Column('mrlMeasuredPpm', sa.String(), nullable=True),
    sa.Column('mrlPermittedPpm', sa.String(), nullable=True),
    sa.Column('prescriptionSigned', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animalId'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['labDispatchId'], ['lab_samples.dispatchId'], ),
    sa.ForeignKeyConstraint(['treatmentId'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dsp_farm', 'farmer_dispatches', ['farmId'], unique=False)
    op.create_index('idx_dsp_status', 'farmer_dispatches', ['status'], unique=False)
    op.create_table('lab_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reportId', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['reportId'], ['lab_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_la_report', 'lab_assessments', ['reportId'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('treatmentId', sa.String(), nullable=False),
    sa.Column('doseTime', sa.DateTime(), nullable=False),
    sa.Column('nowPct', sa.Float(), nullable=True),
    sa.Column('clearLabel', sa.String(), nullable=False),
    sa.Column('productMessage', sa.String(), nullable=False),
    sa.Column('clearsAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treatmentId'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatmentId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    op.drop_index('idx_la_report', table_name='lab_assessments')
    op.drop_table('lab_assessments')
    op.drop_index('idx_dsp_status', table_name='farmer_dispatches')
    op.drop_index('idx_dsp_farm', table_name='farmer_dispatches')
    op.drop_table('farmer_dispatches')
    op.drop_index('idx_trt_phase', table_name='treatments')
    op.drop_index('idx_trt_farm', table_name='treatments')
    op.drop_index('idx_trt_animal', table_name='treatments')
    op.drop_table('treatments')
    op.drop_table('prescription_options')
    op.drop_index('idx_lt_dispatch', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_table('lab_reports')
    op.drop_index('idx_rx_status', table_name='prescriptions')
    op.drop_index('idx_rx_farm', table_name='prescriptions')
    op.drop_index('idx_rx_animal', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('idx_ls_stage', table_name='lab_samples')
    op.drop_table('lab_samples')
    op.drop_index('idx_health_animal', table_name='health_events')
    op.drop_table('health_events')
    op.drop_table('medicine_stocks')
    op.drop_index('idx_animal_species', table_name='animals')
    op.drop_index('idx_animal_farm', table_name='animals')
    op.drop_index('idx_animal_care', table_name='animals')
    op.drop_table('animals')
    op.drop_table('admin_anomalies')
    op.drop_table('vets')
    op.drop_table('farms')
    op.drop_table('users')
    op.drop_table('region_metrics')
    op.drop_table('district_stats')
    # ### end Alembic commands ###
