"""Add condition

Revision ID: 893a29eb66a3
Revises: 2fe9b486ef67
Create Date: 2026-08-24 16:33:33.246790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893a29eb66a3'
down_revision: Union[str, Sequence[str], None] = '2fe9b486ef67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_samples', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('lab_samples', sa.Column('temperature', sa.String(), nullable=True))
    op.add_column('lab_samples', sa.Column('container', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_samples', 'container')
    op.drop_column('lab_samples', 'temperature')
    op.drop_column('lab_samples', 'condition')
    # ### end Alembic commands ###
